version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing npm dependencies...
      - npm ci
      - npm install
      - npm install @aws-sdk/client-transcribe-streaming
      - echo Finished installing npm dependencies.

  build:
    commands:
      - echo Building Angular application...
      - npm run build
      - echo Finished building Angular application.
      - echo Deploying Angular application to S3 bucket...
      - echo Finished deploying Angular application to S3 bucket.
      - echo Listing directory contents...
      - ls -al
      - echo Finished listing directory contents.

artifacts:
  base-directory: dist
  files:
    - '**/*'
